#!/bin/ash
mkdir -p ~/.ssh/ ~/.bin
cd ~/.bin/

cat > on <<eof
#!/bin/ash
for i in {0..204}
do
  curl -sL https://${APP}.herokuapp.com/
  sleep 800
done
eof

cat > up << 'eof'
#!/bin/ash
xxx1=$(stat -c '%Y' ~/.bin/on)
xxx2=$(date +%s)
awk 'BEGIN{printf "%.2f\n",('$(expr $xxx2 - $xxx1)'/3600)}'
# echo $(expr $(expr $xxx2 - $xxx1) / 3600)
eof

chmod +x *

cat > ~/.ssh/finger <<'eoooof'
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCxTF7o0ksdpV8Sasa/HpsTG8JzK446fTpXlezEN1pWwQAAAIjqf3eP6n93
jwAAAAtzc2gtZWQyNTUxOQAAACCxTF7o0ksdpV8Sasa/HpsTG8JzK446fTpXlezEN1pWwQ
AAAEAMSJ1czYcLrNUAyl8nmeEjFOSgY7IR6PrW6CWQEWe+sbFMXujSSx2lXxJqxr8emxMb
wnMrjjp9OleV7MQ3WlbBAAAAA3hAeAEC
-----END OPENSSH PRIVATE KEY-----
eoooof
cat > ~/.ssh/pub <<'eof'
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN8Z3zybD6/YtKyDJ8A4ZUQTfx96UXgQ9OZT5NIPYwde xxx
eof
cat > ~/.ssh/sshd.conf <<'eof'
HostKey ~/.ssh/finger
AuthorizedKeysFile ~/.ssh/pub
Port 1111
ClientAliveInterval 30
ClientAliveCountMax 3
LogLevel QUIET
eof
chmod 600 ~/.ssh/*

cat > vv.json <<eof
{
    "inbounds": [
        {
            "protocol": "vmess",
            "port": 2323,
            "listen":"127.0.0.1",
            "settings": 
            {
                "clients": [{"id": "$UUID","alterId": 0}],
                "disableInsecureEncryption": true
            },
            "streamSettings": 
            {
                "network": "ws",
                "wsSettings": {"path": "/xxx"}
            }
        }
    ],
    "outbounds": [{"protocol": "freedom"}]
}
eof

echo "$(whoami)" > ~/.bin/index.html
cat > Caddyfile <<eof
{
	auto_https off
}
http://127.0.0.1:2222 { 
	root * /home/xxx/.bin
	file_server
reverse_proxy /xxx 127.0.0.1:2323 {
    header_up -Origin
  }
}
eof

$(which sshd) -f ~/.ssh/sshd.conf
vvv -config vv.json 1>/dev/null 2>&1 &
web start -config Caddyfile 1>/dev/null 2>&1 &
echo $?
ps -A
tun server -p $PORT --proxy http://127.0.0.1:2222 1>/dev/null 2>&1



